# **Dataset Link**:-
 https://www.kaggle.com/competitions/jigsaw-toxic-comment-classification-challenge/data

In [1]:
import pandas as pd
import numpy as np

In [2]:
# read all the data
train = pd.read_csv('/content/drive/MyDrive/Datasets/jigsaw_toxic_comment/train.csv')
test = pd.read_csv('/content/drive/MyDrive/Datasets/jigsaw_toxic_comment/test.csv')
test_labels = pd.read_csv('/content/drive/MyDrive/Datasets/jigsaw_toxic_comment/test_labels.csv')
sample = pd.read_csv('/content/drive/MyDrive/Datasets/jigsaw_toxic_comment/sample_submission.csv')

In [3]:
train.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [4]:
test.head()

id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [5]:
test_labels.head(10).iloc[:, 1:]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0     -1            -1       -1      -1      -1             -1
1     -1            -1       -1      -1      -1             -1
2     -1            -1       -1      -1      -1             -1
3     -1            -1       -1      -1      -1             -1
4     -1            -1       -1      -1      -1             -1
5      0             0        0       0       0              0
6     -1            -1       -1      -1      -1             -1
7      0             0        0       0       0              0
8     -1            -1       -1      -1      -1             -1
9     -1            -1       -1      -1      -1             -1

In [6]:
sample.head()

id  toxic  severe_toxic  obscene  threat  insult  \
0  00001cee341fdb12    0.5           0.5      0.5     0.5     0.5   
1  0000247867823ef7    0.5           0.5      0.5     0.5     0.5   
2  00013b17ad220c46    0.5           0.5      0.5     0.5     0.5   
3  00017563c3f7919a    0.5           0.5      0.5     0.5     0.5   
4  00017695ad8997eb    0.5           0.5      0.5     0.5     0.5   

   identity_hate  
0            0.5  
1            0.5  
2            0.5  
3            0.5  
4            0.5

In [7]:
train.isna().sum()

id               0
comment_text     0
toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
dtype: int64

## Converting `text to vectors` to work as `tensors` for model

In [8]:
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 89.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 30.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 78.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.6 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125926 sha256=60290769e7996ecf3c131343d4a6f4d81c61274bd5c96f629f4bd40ac7cf59d1
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers


In [9]:
from sentence_transformers import SentenceTransformer

model0 = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [10]:
embeddings = model0.encode(train['comment_text'])

In [11]:
embeddings

array([[-2.8033113e-02,  5.6779690e-02,  9.1349781e-02, ...,
         1.4138874e-02, -2.6162514e-02, -4.1901261e-02],
       [-5.1319800e-02,  8.7537169e-02,  5.5453263e-02, ...,
         2.0117739e-02, -9.2164256e-02,  1.8548714e-02],
       [ 1.0958090e-02,  9.2102960e-02,  5.1115375e-02, ...,
        -6.0033970e-02,  1.4199837e-02,  9.0343915e-03],
       ...,
       [-5.2935716e-02, -1.7862391e-02, -1.1830753e-01, ...,
        -5.0575245e-02,  1.1459959e-01,  3.1100541e-02],
       [-1.3073631e-04,  2.9176841e-02,  3.0916225e-02, ...,
         3.4936894e-02,  9.2583671e-02,  9.7661503e-02],
       [-3.0522792e-02,  1.3248611e-03,  4.2457968e-02, ...,
         1.5834965e-01, -4.1902486e-02, -3.8564414e-02]], dtype=float32)

In [12]:
embeddings.shape

(159571, 384)

In [13]:
embeddings = embeddings.reshape(159571, 1, 384)
embeddings.shape

(159571, 1, 384)

In [14]:
Y_train = train.iloc[:, 2:].values

In [15]:
Y_train.shape

(159571, 6)

## Now time to create the model using `keras`

In [16]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout, Bidirectional, LSTM

In [17]:
model = Sequential()

model.add(Bidirectional(LSTM(units=64, activation='tanh', input_shape=(1, 384))))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(6, activation='sigmoid'))

In [18]:
model.compile(optimizer="adam", loss="BinaryCrossentropy", metrics=["accuracy"])

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirectiona  (None, 128)              229888    
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               16512     
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                                 
Total params: 313,094
Trainable params: 313,094
Non-trainable params: 0
__________________________________________________

In [22]:
history = model.fit(embeddings, Y_train, epochs=5, validation_split=0.2)

Epoch 1/5
3990/3990 [==============================] - 34s 8ms/step - loss: 0.0451 - accuracy: 0.9842 - val_loss: 0.0540 - val_accuracy: 0.9922
Epoch 2/5
3990/3990 [==============================] - 31s 8ms/step - loss: 0.0422 - accuracy: 0.9845 - val_loss: 0.0552 - val_accuracy: 0.9938
Epoch 3/5
3990/3990 [==============================] - 31s 8ms/step - loss: 0.0395 - accuracy: 0.9772 - val_loss: 0.0571 - val_accuracy: 0.9912
Epoch 4/5
3990/3990 [==============================] - 34s 8ms/step - loss: 0.0366 - accuracy: 0.9730 - val_loss: 0.0600 - val_accuracy: 0.9877
Epoch 5/5
3990/3990 [==============================] - 35s 9ms/step - loss: 0.0340 - accuracy: 0.9761 - val_loss: 0.0615 - val_accuracy: 0.9799


In [23]:
test_embeddings = model0.encode(test.iloc[0].comment_text)

In [25]:
test_embeddings = test_embeddings.reshape(1, 1, 384)

In [26]:
y_pred = model.predict(test_embeddings)

1/1 [==============================] - 1s 796ms/step


In [27]:
test.iloc[0].comment_text

"Yo bitch Ja Rule is more succesful then you'll ever be whats up with you and hating you sad mofuckas...i should bitch slap ur pethedic white faces and get you to kiss my ass you guys sicken me. Ja rule is about pride in da music man. dont diss that shit on him. and nothin is wrong bein like tupac he was a brother too...fuckin white boys get things right next time.,"

In [28]:
test_labels.columns[1:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [29]:
y_pred[0]

array([0.9996475 , 0.4289159 , 0.9947378 , 0.04364538, 0.9802807 ,
       0.838907  ], dtype=float32)

In [30]:
text = "You all bitches are like this, I frigging hate you. And this is my last warning I will kill you in public next time you talk to me like this"
model.predict(model0.encode(text).reshape(1, 1, 384))

1/1 [==============================] - 0s 23ms/step


array([[0.99974567, 0.4914354 , 0.9780944 , 0.83872944, 0.9682888 ,
        0.04986447]], dtype=float32)

In [31]:
def score_comment(comment: str):
    embeddings = model0.encode(comment)
    embeddings = embeddings.reshape(1, 1, 384)
    results = model.predict(embeddings)

    text = ''
    for idx, col in enumerate(test_labels.columns[1:]):
        text += f"{col}: {results[0][idx]>0.5}\n"

    return text

In [32]:
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 56.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.7/65.7 kB 9.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.8/288.8 kB 33.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 kB 10.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 kB 19.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 18.4 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of mdit-py-plugins to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 7.7 MB/s eta 0:00:00
  

In [33]:
import gradio as gr

interface = gr.Interface(fn=score_comment,
                         inputs=gr.inputs.Textbox(lines=10, placeholder="Comment to check Toxicity Score"),
                         outputs="text")

<ipython-input-33-85871b809a8d>:4: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  inputs=gr.inputs.Textbox(lines=10, placeholder="Comment to check Toxicity Score"),
<ipython-input-33-85871b809a8d>:4: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  inputs=gr.inputs.Textbox(lines=10, placeholder="Comment to check Toxicity Score"),
<ipython-input-33-85871b809a8d>:4: GradioDeprecationWarning: `numeric` parameter is deprecated, and it has no effect
  inputs=gr.inputs.Textbox(lines=10, placeholder="Comment to check Toxicity Score"),


In [34]:
interface.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://32363dd33dee9026a7.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
